Harden: Normalize shell dependency loading boilerplate
- REFER:

  https://github.com/DepoXy/sh-source-deps-template#🤞

diff --git a/bin/salvage-fiefdom b/bin/salvage-fiefdom
--- a/bin/salvage-fiefdom
+++ b/bin/salvage-fiefdom
@@ -13,47 +13,111 @@ setup_business_vars () {
 # *** <beg boilerplate `source_deps`: ------------------------------|
 #                                                                   |
 
-source_deps () {
-  local thispth="$1"
-  local prefix="."
-  local depsnok=false
+_salvage_fiefdom__this_filename="salvage-fiefdom"
 
-  _source_it () {
-    local prfx="${1:-.}"
-    local depd="${2:-.}"
-    local file="${3:-.}"
-    local path="${prfx}/${depd}/${file}"
-    if command -v "${file}" > /dev/null; then
-      # Use version found on PATH.
-      . "${file}"
-    elif [ -f "${path}" ]; then
-      # Fallback on local deps/ copy.
-      # NOTE: `dash` complains if missing './'.
-      . "${path}"
-    else
-      local depstxt=''
-      [ "${prfx}" != "." ] && depstxt="in ‘${prfx}/${depd}’ or "
-      >&2 echo "MISSING: ‘${file}’ not found ${depstxt}on PATH."
-      depsnok=true
-    fi
-  }
+_salvage_fiefdom__source_deps () {
+  local sourced_all=true
 
-  # Allow user to symlink executables and not libraries.
-  # E.g., `ln -s /path/to/bin/logger.sh /tmp/logger.sh ; /tmp/logger.sh`
-  # knows that it can look relative to /path/to/bin/ for sourceable files.
-  [ -n "${thispth}" ] && prefix="$(dirname -- "$(realpath -- "${thispth}")")"
+  # On Bash, user can source this file from anywhere.
+  # - If not Bash, user must `cd` to this file's parent directory first.
+  local prefix="$(dirname -- "${_salvage_fiefdom__this_fullpath}")"
+
+  # USAGE: Load dependencies using path relative to this file, e.g.:
+  #   _source_file "${prefix}" "../deps/path/to/lib" "dependency.sh"
 
   #                                                                 |
   # *** stop boilerplate> ------------------------------------------|
 
   # Load `print_nanos_now`.
-  _source_it "${prefix}" "../deps/sh-print-nanos-now/bin" "print-nanos-now.sh"
+  _salvage_fiefdom__source_file "${prefix}" "../deps/sh-print-nanos-now/bin" "print-nanos-now.sh"
 
   # *** <more boilerplate: -----------------------------------------|
   #                                                                 |
 
-  ! ${depsnok}
+  ${sourced_all}
 }
+
+_salvage_fiefdom__smells_like_bash () { declare -p BASH_SOURCE > /dev/null 2>&1; }
+
+_salvage_fiefdom__print_this_fullpath () {
+  if _salvage_fiefdom__smells_like_bash; then
+    echo "$(realpath -- "${BASH_SOURCE[0]}")"
+  elif [ "$(basename -- "$0")" = "${_salvage_fiefdom__this_filename}" ]; then
+    # Assumes this script being executed, and $0 is its path.
+    echo "$(realpath -- "$0")"
+  else
+    # Assumes cwd is this script's parent directory.
+    echo "$(realpath -- "${_salvage_fiefdom__this_filename}")"
+  fi
+}
+
+_salvage_fiefdom__this_fullpath="$(_salvage_fiefdom__print_this_fullpath)"
+
+_salvage_fiefdom__shell_sourced () {
+  [ "$(realpath -- "$0")" != "${_salvage_fiefdom__this_fullpath}" ]
+}
+
+_salvage_fiefdom__source_file () {
+  local prfx="${1:-.}"
+  local depd="${2:-.}"
+  local file="${3:-.}"
+
+  local deps_dir="${prfx}/${depd}"
+  local deps_path="${deps_dir}/${file}"
+
+  # Just in case sourced file overwrites top-level `_salvage_fiefdom__this_filename`,
+  # cache our copy, should we need it for an error message.
+  local _this_file_name="${_salvage_fiefdom__this_filename}"
+
+  if [ -f "${deps_path}" ]; then
+    # SAVVY: Source files from their dirs, so they can find their deps.
+    local before_cd="$(pwd -L)"
+    cd "${deps_dir}"
+    # SAVVY: If errexit, error while sourcing kills process immediately,
+    # and error you see might indicate this source file, but the line
+    # number for the file being sourced. E.g.,
+    #   /path/to/bin/myapp: 442: export: Illegal option -f
+    # where `442` is line number from, e.g., 'deps/lib/dep.sh'.
+    if ! . "${deps_path}"; then
+      >&2 echo "ERROR: Dependency ‘${file}’ returned nonzero when sourced"
+      sourced_all=false
+    fi
+    cd "${before_cd}"
+  else
+    local depstxt=""
+    [ "${prfx}" = "." ] || depstxt="in ‘${deps_dir}’ or "
+    >&2 echo "ERROR: ‘${file}’ not found under ‘${deps_dir}’"
+    if _salvage_fiefdom__smells_like_bash; then
+      >&2 echo "- GAFFE: This looks like an error with the ‘_salvage_fiefdom__source_file’ arguments"
+    else
+      >&2 echo "- HINT: You must source ‘${_this_file_name}’ from its parent directory"
+    fi
+    sourced_all=false
+  fi
+}
+
+# BONUS: You can use these aliases instead of the uniquely-named functions,
+# just be aware not to call any alias after calling _source_deps.
+_shell_sourced () { _salvage_fiefdom__shell_sourced; }
+_source_deps () { _salvage_fiefdom__source_deps; }
+
+_salvage_fiefdom__source_deps_unset_cleanup () {
+  unset -v _salvage_fiefdom__this_filename
+  unset -f _salvage_fiefdom__print_this_fullpath
+  unset -f _salvage_fiefdom__shell_sourced
+  unset -f _shell_sourced
+  unset -f _salvage_fiefdom__smells_like_bash
+  unset -f _salvage_fiefdom__source_deps
+  unset -f _source_deps
+  unset -f _salvage_fiefdom__source_deps_unset_cleanup
+  unset -f _salvage_fiefdom__source_file
+}
+
+# USAGE: When this file is being executed, before doing stuff, call:
+#   _source_deps
+# - When this file is being sourced, call both:
+#   _source_deps
+#   _salvage_fiefdom__source_deps_unset_cleanup
 
 #                                                                   |
 # *** end boilerplate `source_deps`> -------------------------------|
@@ -1038,32 +1102,49 @@ salvage-fiefdom () {
 
 # ***
 
-function errexit_cleanup () {
-  local exit_code=$?
-  # Skip `workdir_expunge` on error; assume user will run again.
-  workdir_rmdir_if_empty
-  exit ${exit_code}
+exitcode=0
+
+errexit_cleanup () {
+  exitcode=$?
+  exit_with_cleanup
 }
-trap -- errexit_cleanup EXIT
+
+exit_with_cleanup () {
+  # Unhook errexit_cleanup.
+  trap - EXIT
+
+  # Skip `workdir_expunge` on error;
+  #   assume user will run again.
+  workdir_rmdir_if_empty
+
+  exit ${exitcode}
+}
 
 main () {
-  local exitcode=0
+  set -e
+  
+  _source_deps
+
   setup_business_vars
-  # $0 is `bash` when this file sourced; else it's this file.
-  # Whereas ${BASH_SOURCE[0]} always references this file.
-  source_deps "${BASH_SOURCE[0]}" || return 1
-  if [ "${BASH_SOURCE[0]}" != "$0" ]; then
-    # Being sourced, so expose the function, but do not call.
-    export -f salvage-fiefdom
-  else
-    salvage-fiefdom "${@}"
-    exitcode=$?
-  fi
-  return ${exitcode}
+
+  trap -- errexit_cleanup EXIT
+
+  salvage-fiefdom "$@" \
+    || exitcode=$?
+
+  exit_with_cleanup
 }
 
-main "${@}"
+if _shell_sourced; then
+  _source_deps
+  setup_business_vars
+else
+  main "$@"
+fi
 
-# Unhook errexit_cleanup.
-trap - EXIT
+_salvage_fiefdom__source_deps_unset_cleanup
+unset -v exitcode
+unset -f errexit_cleanup
+unset -f exit_with_cleanup
+unset -f main
 
